### ISSUE TITLE
Events are not sorted properly

### ISSUE THREAD

**Issue by andykog** [wix/DetoxInstruments#16]
Events should be sorted by start time:
<img width="684" alt="screen shot 2018-11-28 at 14 23 28" src="https://user-images.githubusercontent.com/6760207/49211713-dd809380-f3c8-11e8-853e-ca9d78af7ab7.png">

**Comment by LeoNatan** [comment]
So apparently it's not a bug in the algorithm, just very short events which are 0px wide.

**Comment by LeoNatan** [comment]
I will make 0 duration events have a 0.0001s appearance so that they are visible if you zoom in enough.
