### ISSUE TITLE
Crash when trying to discover apps for profiling

### ISSUE THREAD

**Issue by vilvil** [wix/DetoxInstruments#17]
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c2841bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010b094735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c1d04ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010c1ac775 -[__NSArrayM insertObject:atIndex:] + 1269
	4   DTXProfiler                         0x00000001078bd973 -[DTXSocketConnection _writeDataNow:completionHandler:] + 286
	5   libdispatch.dylib                   0x0000000112a0f595 _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x0000000112a10602 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x0000000112a17b0b _dispatch_lane_serial_drain + 791
	8   libdispatch.dylib                   0x0000000112a18784 _dispatch_lane_invoke + 428
	9   libdispatch.dylib                   0x0000000112a2289a _dispatch_workloop_worker_thread + 733
	10  libsystem_pthread.dylib             0x0000000112dff61c _pthread_wqthread + 409
	11  libsystem_pthread.dylib             0x0000000112dff415 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vilvil** [comment]
<img width="621" alt="2018-11-29 19 20 37" src="https://user-images.githubusercontent.com/3429098/49218626-e6df1f80-f40b-11e8-8358-17d88ebe2d9e.png">

**Comment by LeoNatan** [comment]
Thanks

**Comment by vilvil** [comment]
it can discover app in demo ,but can't discover app in my own app

**Comment by LeoNatan** [comment]
Is this crash in Detox Instruments or in your own app?

**Comment by vilvil** [comment]
in my own app

**Comment by vilvil** [comment]
![2018-11-30 14 59 48](https://user-images.githubusercontent.com/3429098/49273769-0714ea00-f4b1-11e8-906e-ba4ee2c5487e.png)
![2018-11-30 15 00 11](https://user-images.githubusercontent.com/3429098/49273770-0714ea00-f4b1-11e8-921a-f4a99851336e.png)
![2018-11-30 15 00 31](https://user-images.githubusercontent.com/3429098/49273772-0714ea00-f4b1-11e8-9830-39e233ed0ba6.png)
![2018-11-30 15 01 14](https://user-images.githubusercontent.com/3429098/49273773-0714ea00-f4b1-11e8-8627-b778e19e97da.png)
![2018-11-30 15 01 57](https://user-images.githubusercontent.com/3429098/49273774-07ad8080-f4b1-11e8-92ca-c4762ce89eaa.png)

**Comment by LeoNatan** [comment]
Thanks for the info!
Can you please say what device or simulator are you running?
Could you also print `cmd` fully?

**Comment by vilvil** [comment]
simulator , 
![2018-11-30 18 42 53](https://user-images.githubusercontent.com/3429098/49284537-d7c1a580-f4cf-11e8-8e0f-ca1e84a87425.png)

**Comment by LeoNatan** [comment]
I am assuming that <null> is the problem. It's very strange, there was a bug in the code that set it to `0` instead of `@0`, but it has never crashed before. I will release a new version soon to test.

**Comment by LeoNatan** [comment]
@vilvil Please try on the latest version.

**Comment by vilvil** [comment]
now it can discover my app, but there is a new crash
<img width="614" alt="2018-12-03 10 13 42" src="https://user-images.githubusercontent.com/3429098/49349245-c00f3a80-f6e4-11e8-9b8f-0e6a923befb5.png">
![2018-12-03 10 07 29](https://user-images.githubusercontent.com/3429098/49349256-c998a280-f6e4-11e8-9e00-94903c5ca702.png)
![2018-12-03 10 08 02](https://user-images.githubusercontent.com/3429098/49349259-cbfafc80-f6e4-11e8-89ef-29dd6002f62d.png)

**Comment by LeoNatan** [comment]
Can you please expand the stack trace so I can see where it crashes internally? Thanks

**Comment by LeoNatan** [comment]
Ping @vilvil

**Comment by LeoNatan** [comment]
Perhaps enable exception breakpoint and show me that stack trace. I think the screenshot is after someone has already caught the inner exception. Thanks

**Comment by vilvil** [comment]
![2018-12-06 18 05 33](https://user-images.githubusercontent.com/3429098/49577126-b8b88d00-f981-11e8-9a3d-441f35cb515b.png)
![Uploading 屏幕快照 2018-12-06 18.05.49.png…]()

**Comment by LeoNatan** [comment]
There is something wrong with serializing the recording object from your app.

Could I trouble you to put a break point on `_serializeCommandWithSelector:entityName:dict:additionalParams:` and `po obj`? Thanks

**Comment by LeoNatan** [comment]
Something is confusing the plist serializer to fail. I've already added more info there, but if you have the sources, you can replace the few lines there with:

```
NSError* err;
	NSData* plistData = [NSPropertyListSerialization dataWithPropertyList:cmd format:NSPropertyListBinaryFormat_v1_0 options:0 error:&err];
	
	NSAssert(plistData != nil, @"Unable to encode data to property list: %@", err.localizedDescription);
```

This should print which field exactly fails.

**Comment by LeoNatan** [comment]
Thank you again for your patience and helping me debug!

**Comment by vilvil** [comment]
![2018-12-07 09 48 09](https://user-images.githubusercontent.com/3429098/49622752-c57ec480-fa05-11e8-9639-e0df22bf18f2.png)

**Comment by vilvil** [comment]
@LeoNatan

**Comment by LeoNatan** [comment]
I still don't see the issue. The data seems fine to me.

Could you please try triggering the crash again with the latest source/release? It should print a helpful error message with exactly what is failing to serialize. Thank you!

**Comment by LeoNatan** [comment]
Closing the issue. Please reopen if you are able to provide the above requested information.
