### ISSUE TITLE
need support for undefined arguments when JS calls a native hook 

### ISSUE THREAD

**Issue by kezax94** [wix/DetoxInstruments#23]
when JS calls a native hook with an undefined argument, this exception occurs in Detox before calling the hook:

2018-12-18 17:01:53.800763+0200 WixOneAppDev[84537:45278301] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
    0   CoreFoundation                      0x000000010f5731e6 __exceptionPreprocess + 294
    1   libobjc.A.dylib                     0x000000010da54031 objc_exception_throw + 48
    2   CoreFoundation                      0x000000010f5b30bc _CFThrowFormattedException + 194
    3   CoreFoundation                      0x000000010f4a22a9 -[__NSArrayM insertObject:atIndex:] + 1273
    4   DTXProfiler                         0x000000010bc244d8 ____dtx_JSObjectMakeFunctionWithCallback_block_invoke + 489
    5   CoreFoundation                      0x000000010f4f6ccc __invoking___ + 140
    6   CoreFoundation                      0x000000010f4f6b84 -[NSInvocation invoke] + 308
    7   JavaScriptCore                      0x00000001115fad38

**Comment by LeoNatan** [comment]
Thanks
