### ISSUE TITLE
Make "Zoom In" (Cmd+Plus) follow mouse cursor as an origin for zooming

### ISSUE THREAD

**Issue by noomorph** [wix/DetoxInstruments#30]
**Is your feature request related to a problem? Please describe.**

As of now, "Zoom In" (Cmd+Plus) always zooms towards the center of the timeline which is not convenient when you work without a trackpad and have no means to resort to the default pinch-to-zoom gesture.

**Describe the solution you'd like**

An implementation of "Zoom In" command could have used a mouse cursor position on the timeline as an origin for zooming.

<img src="https://user-images.githubusercontent.com/1962469/50977892-e56d4080-14fb-11e9-95d0-a3969008b425.jpg" height=200>

**Describe alternatives you've considered**

Alternatively, using a selected X coordinate (via previous mouse click) as an origin could have also worked out, I guess.

<img src="https://user-images.githubusercontent.com/1962469/50977924-f4ec8980-14fb-11e9-8ee2-ef8526153a6b.jpg" height=200>

**Comment by LeoNatan** [comment]
Agreed, the current behavior is not optimal. It was a quick implementation to allow users without a trackpad to be able to zoom in. I will have to play around to see what makes more sense, taking the user cursor always, or if there is a selection on the plot, zoom toward that.
