### ISSUE TITLE
Cmd+1 and Cmd+2 do not make Inspectors appear if they had been previously closed

### ISSUE THREAD

**Issue by noomorph** [wix/DetoxInstruments#31]
**Describe the bug**

Cmd+1 and Cmd+2 do not make Inspectors appear if they had been previously closed.

**To Reproduce**

1. Make sure one of the inspectors (see bottom-right corner) is active, as on the screenshot.
2. Click on the "Show or hide the inspectors" button (marked with a black arrow on the screenshot).
3. Make sure the inspector now is hidden.
4. Click Cmd+1 or Cmd+2 shortcuts (View -> Inspectors -> Show Extended Detail or another one).
5. Look at the inspectors - they are still hidden.

**Expected behavior**

5. The chosen inspector should appear according to the shortcut (Cmd+1 or Cmd+2) 

**Screenshots**

<img width="1259" alt="screen shot 2019-01-21 at 5 26 13 pm" src="https://user-images.githubusercontent.com/1962469/51483652-402b5580-1da2-11e9-9801-158444880faa.png">

**Comment by LeoNatan** [comment]
Fixed 😜
