### ISSUE TITLE
Detox Instruments crashed in the midst of profiling a React Native app

### ISSUE THREAD

**Issue by noomorph** [wix/DetoxInstruments#32]
**Describe the bug**

Detox Instruments crashed in the midst of profiling a React Native app.

**Crash dump**

See: [detox_crash_21_jan_2019.txt](https://github.com/wix/DetoxInstruments/files/2779613/detox_crash_21_jan_2019.txt)

**Comment by LeoNatan** [comment]
I think this was already fixed in https://github.com/wix/DetoxInstruments/commit/7d90af1c1f871ae062d244c567c9ee896d6bc387 but I'll take another look.
