### ISSUE TITLE
Some network requests are duplicated

### ISSUE THREAD

**Issue by emilisb** [wix/DetoxInstruments#34]
In one of my projects all network requests to a server are shown twice. This bug is a bit tricky to reproduce because not all domains are affected.

![screenshot 2019-02-14 at 12 35 50](https://user-images.githubusercontent.com/13116854/52798622-fbcd6580-3080-11e9-9ee2-6bbc3590df1c.png)

**Mac (please complete the following information):**
 - Model: MacBook Pro 2018
 - OS: macOS 10.14.0
 - Xcode: 9.4.1

**iOS Device (please complete the following information):**
 - Model: iOS Simulator
 - OS: iOS 11.4
 - Xcode: 9.4.1

**Additional context**
wix-one-app-contacts is one of the affected modules, you can use it to replicate the issue.

**Comment by LeoNatan** [comment]
Thanks

**Comment by LeoNatan** [comment]
I managed to reproduce this issue. Will look to fix.

**Comment by LeoNatan** [comment]
Fixed in 3fb485553cc7611f8a8b817deb133466cc9157af
