### ISSUE TITLE
Ability to send network requests

### ISSUE THREAD

**Issue by viktorijasujetaite** [wix/DetoxInstruments#36]
Network Activity Instrument provides ability to record network requests. It would be great if there was:
- ability to send requests;
- ability to get piece of code to make such request in specific language/library (e.g. NodeJS request);

This would replace the need to use Postman or similar tools as addition to DetoxInstruments.

**Comment by LeoNatan** [comment]
Thanks.

**Comment by LeoNatan** [comment]
@viktorijasujetaite Could you please upload a screenshot of how you Postman UI looks when you perform these steps?
Thanks

**Comment by viktorijasujetaite** [comment]
<img alt="postman_example" src="https://user-images.githubusercontent.com/32874605/53476218-80a18180-3a7a-11e9-90c4-ddcb862d9d18.png">

Marked key elements in green: request type dropdown, send button, etc. Second screen - what you see after taping on "code" button. Marked in green - snippet type chooser.

**Comment by LeoNatan** [comment]
Great, thanks!

**Comment by LeoNatan** [comment]
What I have so far:

<img width="760" alt="screen_shot_2019-03-07_at_08 58 56" src="https://user-images.githubusercontent.com/2270433/53938247-3cd0fc80-40b8-11e9-9d2c-06d1ce99447d.png">

Still missing docs, export to curl/node, response handling in case it's not text, etc. But works well.

**Comment by viktorijasujetaite** [comment]
Thanks, I'll try it out next week!

**Comment by LeoNatan** [comment]
It has not been released yet. I am hoping to release early next week.

**Comment by LeoNatan** [comment]
Initial version implemented in v1.10.9989

There is support for copying code snippets for curl or node.

I will be improving this utility with time.
