### ISSUE TITLE
Bridge Call Counters / Bridge Data Counters not showing up

### ISSUE THREAD

**Issue by fossage** [wix/DetoxInstruments#4]
**DETOX INSTRUMENTS VERSION:**   0.9.1
**REACT NATIVE VERSION:**  0.54.4

First off, great tool!  

I've recently started using it on an existing React Native project and I cannot seem to get the `Bridge Call Counters` and `Bridge Data Counters` portion of the profiler to capture any data.  I have ensured that I have the `Profile React Native` options selected, and all of the other profiling seems to work just fine.  Just for good measure I have also made sure to delete my existing `Build` directory, cleaned the project, and cleaned out the `Derived Data` folder.

Is this something anyone else has run into?  Is there something I'm potentially missing in the setup phase?

<img width="1428" alt="screenshot 2018-07-16 12 51 14" src="https://user-images.githubusercontent.com/8979334/42780961-9bfb7036-88f9-11e8-974a-377c1d51ee10.png">

**Comment by LeoNatan** [comment]
Thank you for using Detox Instruments.
I am not sure why it's not working. I will check tomorrow with your RN version. I have been testing this tool with 0.51.x because this is what we use internally, so most likely something changed in RN that rendered the profiler framework not handling RN properly.

**Comment by LeoNatan** [comment]
@fossage I just tested with React Native 0.54.4 and in my test app, counters and data are captured correctly.

Could you please try to reproduce on a new project and see if it still reproduces.

**Comment by fossage** [comment]
@LeoNatan , it appears to work correctly in a new project.  The project I'm currently trying to use it in is fairly mature and contains numerous native dependencies, so perhaps its one of these that is causing the issue.  I'll see if I can work back through the git history an get it working at some point in time.  If so, I'll see if I can pinpoint what change/dependency addition is causing it not to work and report back.

**Comment by LeoNatan** [comment]
As long as the dependencies don't intervene with how RN registers its JavaScriptCore stuff, they shouldn't interfere.

**Comment by fossage** [comment]
Well this is embarrassing.  After a morning of jumping down various rabbit holes I realized I had remote JS debugging enabled.  Problem solved!

**Comment by LeoNatan** [comment]
Ahhh hehehe, yep that will do it, and I didn't think about it as well. That's one of the main issues we had with remove debugging—it's not on the device. Using Instruments, this should help you. If you have suggestions to functionality, please open enhancement requests.
