### ISSUE TITLE
didFinishCollectingMetrics crash 

### ISSUE THREAD

**Issue by artald** [wix/DetoxInstruments#41]
2019-03-25 11:14:40.437328+0200 WixOneAppDev[70051:7189028] -[RCTHTTPRequestHandler URLSession:task:didFinishCollectingMetrics:]: unrecognized selector sent to instance 0x6000000e10e0
2019-03-25 11:14:42.429356+0200 WixOneAppDev[70051:7189028] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTHTTPRequestHandler URLSession:task:didFinishCollectingMetrics:]: unrecognized selector sent to instance 0x6000000e10e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ad231bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000108ce9735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ad41f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010ad27c34 ___forwarding___ + 772
	4   CoreFoundation                      0x000000010ad29da8 _CF_forwarding_prep_0 + 120
	5   CFNetwork                           0x000000010a090c90 __68-[NSURLSession delegate_task:didFinishCollectingMetrics:completion:]_block_invoke + 38
	6   Foundation                          0x0000000108756f9e __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	7   Foundation                          0x0000000108756ea5 -[NSBlockOperation main] + 68
	8   Foundation                          0x0000000108753c14 -[__NSOperationInternal _start:] + 689
	9   Foundation                          0x0000000108759c4b __NSOQSchedule_f + 227
	10  libdispatch.dylib                   0x0000000110b50595 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x0000000110b51602 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000110b58b0b _dispatch_lane_serial_drain + 791
	13  libdispatch.dylib                   0x0000000110b59784 _dispatch_lane_invoke + 428
	14  libdispatch.dylib                   0x0000000110b6389a _dispatch_workloop_worker_thread + 733
	15  libsystem_pthread.dylib             0x0000000110f4160b _pthread_wqthread + 409
	16  libsystem_pthread.dylib             0x0000000110f41405 start_wqthread + 13
)

**Comment by LeoNatan** [comment]
Thanks, will fix now.
