### ISSUE TITLE
Unable to build app after integrating, profiler_build_phase.sh script failure

### ISSUE THREAD

**Issue by szymon-kazmierczak** [wix/DetoxInstruments#47]
**Description**
Having followed the integration steps (added linker flags, added run script), after building, i get the following error.

```/Applications/Detox Instruments.app/Contents/SharedSupport/Scripts/profiler_build_phase.sh: line 16: syntax error near unexpected token `('```

Running detox instruments version v1.11.b10669 

**Steps to Reproduce**
1. Integrate detox instruments with an app
2. build the app

*Environment**
 - Model: MacBook Pro 2017
 - OS: macOS 10.14.5
 - Xcode: Xcode 10.1

**iOS Device (please complete the following information):**
 - Model: iPhone XR simulator 
 - OS: 12.2
 - Xcode: Xcode 10.1

**Additional Context**

**Comment by LeoNatan** [comment]
Apologies, I found the error. I tested the commands on zsh but not on bash, and in this instance, the two shells deviated in these commands.

**Comment by LeoNatan** [comment]
Please update to v1.11.10670 and let me know.

**Comment by szymon-kazmierczak** [comment]
All good now!
