### ISSUE TITLE
Handle network responses in a more readable way

### ISSUE THREAD

**Issue by talBebchuk** [wix/DetoxInstruments#48]
hey,
currently, in order to view the responses in the detox instrument network section, we need to open a file and read (or parse manually) a string.

in chrome devtool, for example, if the response is an object (or a JSON object), it's parsed in the 'preview' tab so it's more readable and easy to use.

**Comment by LeoNatan** [comment]
👍

**Comment by LeoNatan** [comment]
Can you please suggest common types of files, other than JSON, that would be good to support?

**Comment by LeoNatan** [comment]
Implemented in 1.11.10815
