### ISSUE TITLE
Will it support to collect performance data of any iOS App processes running on iPhone without source code ?

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#49]
DetoxInstruments is a wonderful tool to analyze the iOS App performance based on the source code. Sometimes developers want to compare the performance with competing App products without source code.So is there any method to collect performance data of any iOS Apps without source code ?

**Comment by LeoNatan** [comment]
Hello,

The profiler framework (and Detox Instruments in general) is an in-process method of data collection. So it is not normally possible to collection information of an app that runs without the Profiler framework integrated.

In a jailbroken device, you can inject the profiler framework using DYLD_INSERT_LIBRARIES or similar strategies, at which point you should be able to connect and collection performance information.

Cheers

**Comment by YY-Wei** [comment]
> Hello,
> 
> The profiler framework (and Detox Instruments in general) is an in-process method of data collection. So it is not normally possible to collection information of an app that runs without the Profiler framework integrated.
> 
> In a jailbroken device, you can inject the profiler framework using DYLD_INSERT_LIBRARIES or similar strategies, at which point you should be able to connect and collection performance information.
> 
> Cheers

Thank you very much for your detailed reply:)
