### ISSUE TITLE
'CLI/ObjCCLIInfra' did not contain a6c73210f37f2a5d1eabc9efb79af156b0b6d5b1.

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#52]
1.error: Server does not allow request for unadvertised object a6c73210f37f2a5d1eabc9efb79af156b0b6d5b1
Fetched in submodule path 'CLI/ObjCCLIInfra', but it did not contain a6c73210f37f2a5d1eabc9efb79af156b0b6d5b1. Direct fetching of that commit failed.

2.DetoxInstruments git:(master) ✗ git submodule
+445657e1ecf399a19b1ae998a69ee38d9c86deb4 CLI/ObjCCLIInfra (heads/master)'
this is the same as the latest commit of 'https://github.com/wix/ObjCCLIInfra.git'

**Comment by LeoNatan** [comment]
Thanks, I will take a look soon.

**Comment by LeoNatan** [comment]
Apologies, forgot to push my commit in the submodule. Try now.

**Comment by YY-Wei** [comment]
> Apologies, forgot to push my commit in the submodule. Try now.

Thanks very much.
