### ISSUE TITLE
After upgrading to v1.11.10819, Detox Instruments cannot quit normally.

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#54]
**Environment**
 - Model: MacBook Pro 2018 15-inch
 - OS: macOS 10.14.6(18G95)
 - Xcode: Xcode 10.3

After upgrading to v1.11.10819, Detox Instruments cannot quit normally, it can quit by forced termination.

**Comment by LeoNatan** [comment]
Does the application not respond after trying to quit?

**Comment by YY-Wei** [comment]
> Does the application not respond after trying to quit?

Yes. Then I restart macOS, it can not respond after trying to quit too.

**Comment by LeoNatan** [comment]
All Mac is not responding?

**Comment by LeoNatan** [comment]
I added some embedded fonts in the application. I wonder if something in the text tenderer is causing this.

**Comment by YY-Wei** [comment]
> All Mac is not responding?

Oh, man, I find the bug replay path:
(1)quit from the menu"Quit Detox Instruments", it can not quit.
(2)If I click the "Cancel" button, it can quit.

**Comment by LeoNatan** [comment]
I’m not sure I understand. Is this when you have a new document open and the select app screen is open?

**Comment by YY-Wei** [comment]
> I’m not sure I understand. Is this when you have a new document open and the select app screen is open?

![image](https://user-images.githubusercontent.com/54052330/65315767-3d9c2c80-dbcb-11e9-9947-f3f209ea1a0e.png)

When I launch Detox Instruments as above, then I click the menu"Quit Detox Instruments"it can not quit. You mean this is a feature, not a bug, right? ：）

**Comment by LeoNatan** [comment]
Haha, this is actually a feature of macOS, where modal windows block the application from quitting. But I have some property set that disables this behavior. I will check.

**Comment by LeoNatan** [comment]
https://github.com/wix/DetoxInstruments/blob/54c865e28593aa701627d3580d6062b52d9d3164/DetoxInstruments/DetoxInstruments/RemoteProfiling/DTXRecordingTargetPickerViewController.m#L130

It is being set.

**Comment by LeoNatan** [comment]
On my machine, with macOS Catalina (10.15) this works as expected, and worked as expected on 10.14 as well in the past.

**Comment by LeoNatan** [comment]
Well, even after my change, it still blocks quit under Mojave (I ran it in a VM). Not sure what's going on. Will install Xcode in the VM to see.

**Comment by LeoNatan** [comment]
This seems like a Mojave bug. I've reproduced but unclear why. On Catalina (and older builds of Mojave), this works as expected.
