### ISSUE TITLE
The method Profiler Framework calculate the memory seems to be a little more complex than the method Apple Staff suggest.

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#55]
Hello Leo:

Our discuss before is here:https://github.com/wix/DetoxInstruments/issues/53. 

Now I find something new about the method of calculate the memory.

The method Profiler Framework calculate the memory(and the method from debugserver) seems to be a little more complex than the method Apple Staff suggest。
The method from Apple Staff:https://forums.developer.apple.com/message/357415#357415（Re: how XCode to calculate Memory）.It just return vmInfo.phys_footprint.

The definition of phys_footprint:
https://github.com/apple/darwin-xnu/blob/master/osfmk/kern/task.c#L914

You can learn more about the philosophy behind this in WWDC 2018 Session 416 [iOS Memory Deep Dive](https://developer.apple.com/videos/play/wwdc2018/416/)

**Comment by LeoNatan** [comment]
Ha, this is actually even better! It's the same result that is shown when running an application in Xcode. 

I header it says `/* added for rev1 */`. I wonder what that means.

**Comment by LeoNatan** [comment]
Using `phys_footprint` now.
