### ISSUE TITLE
About analyzing the performance of the Launching process.

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#56]
It seems that is is not convenient to use Detox Instruments to analyze performance of the App Launching process. Because when the app shows in the "Select an app to profile" window, the app has launched.

**Comment by LeoNatan** [comment]
That is correct. Live profiling is currently not suitable for launch analysis. To profile launch, use the `DTXProfiler` API to start a recording somewhere very early (like `+load` or `__attribute__((constructor))`) and stop recording somewhere late. You can then pull the recording from the device using the app management tools.

**Comment by LeoNatan** [comment]
I don't really have good ideas how to do this, as iOS is a very closed system. If you have ideas, please share.

**Comment by LeoNatan** [comment]
I've implemented app launch profiling. It will be out in the next version of Detox Instruments and profiler. You will have the option to start an app launch profiling from the UI, and then see the results in the UI once the configurable time has passed. Thanks
