### ISSUE TITLE
A mistake in 'Update Build Numbers Script' in Build Phases of DetoxInstruments and DTXProfiler targets.

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#57]
Build ERROR:
`$(CURRENT_PROJECT_VERSION) + 1: syntax error: operand expected (error token is "$(CURRENT_PROJECT_VERSION) + 1")
`

Because 
`buildNumber=$(($buildNumber) + 1) ` is wrong.

You should change it to:
`buildNumber=$(($($buildNumber) + 1))`

**Comment by LeoNatan** [comment]
What is the difference between `$buildNumber` and `$($buildNumber))`? For me the scripts work.

**Comment by YY-Wei** [comment]
> What is the difference between `$buildNumber` and `$($buildNumber))`? For me the scripts work.

sorry. It looks like it is a Xcode build bug. Just now, I use `$buildNumber)` to rerun, it was OK. But about 30min ago , it was wrong and show the tips 'syntax error' above.How odd!
