### ISSUE TITLE
The profiler version linked in app is incompatible with the current version of Detox Instruments.

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#58]
When use [IPAPatch](https://github.com/Naituw/IPAPatch)(which provide a simple way to patch iOS Apps, without needing to jailbreak.) to link Profiler Framework in the app, the app can run normally, but Detox Instruments Client always shows incompatible problem:

![image](https://user-images.githubusercontent.com/54052330/65423335-514dca00-de3b-11e9-947e-1cb30cbc0f37.png)

It seems that Detox Instruments Client can not get the value of the profiler framework version.

DTXProfiler Target build under Xcode 11:
- Version: 1.11
- Build: 10819

**Comment by LeoNatan** [comment]
This is a bug in your end. Make sure to link to the entire framework, not just the binary. The version is obtained from the Info.plist.

**Comment by YY-Wei** [comment]
> This is a bug in your end. Make sure to link to the entire framework, not just the binary. The version is obtained from the Info.plist.

Actually I have linked the entire framewor including the Info.plist and other files such as 'Headers' and so on.

**Comment by LeoNatan** [comment]
https://github.com/wix/DetoxInstruments/blob/b01b58e102cafa4751cb944c26e0b9e313f7b60f/Profiler/DTXProfiler/Utilities/DTXDeviceInfo.m#L100

Put a breakpoint here and see what the bundle returned is.

**Comment by YY-Wei** [comment]
I check the Info.plist diff:

![image](https://user-images.githubusercontent.com/54052330/65424870-2e251980-de3f-11e9-9d41-5082f8eb4e65.png)

the right one is the normal Info.plist, the left one builded under Xcode 11 seems to lost the 'Bundle Version' field.

**Comment by LeoNatan** [comment]
I’ve already released a version with Xcode 11 and it works. Check what the version scripts are doing on your end.

**Comment by YY-Wei** [comment]
> https://github.com/wix/DetoxInstruments/blob/b01b58e102cafa4751cb944c26e0b9e313f7b60f/Profiler/DTXProfiler/Utilities/DTXDeviceInfo.m#L100
> 
> Put a breakpoint here and see what the bundle returned is.

When I run Detox Instruments, it can not attach and just finish running without showing the Client, need any other settings to run from Xcode ? So I can check the break point value.

**Comment by LeoNatan** [comment]
Attaching Xcode to Detox Instruments won’t help as the above line runs in the app context. You need to somehow attach Xcode to your IPAPatched app with the Profiler framework.

**Comment by YY-Wei** [comment]
> Attaching Xcode to Detox Instruments won’t help as the above line runs in the app context. You need to somehow attach Xcode to your IPAPatched app with the Profiler framework.

Thanks, I will try this.

Type of DTXProfiler(exec) in DTXProfiler.framework from Detox Instruments.app installed by brew cask is data,but the type of same file in DTXProfiler.framework  builded by Xcode is Mach-O.
Is this designed for some reason?

**Comment by LeoNatan** [comment]
Yes, this is on purpose. Apple's notarization service doesn't support having an iOS binary inside the macOS bundle, so I encrypt the binary. In Detox Instruments, when you select "Show Profiler Framework" in the Help menu, it decrypts it and gives you a copy you can use. When you follow the integration guide, the scripts also decrypt before usage. Of course, if you build normally using Xcode, you also get a binary file.

**Comment by YY-Wei** [comment]
> when you select "Show Profiler Framework" in the Help menu, it decrypts it and gives you a copy you can use

I did this,  it did decrypt the framework and gives me a copy, but the DTXProfile(exec) in the copy is 0 KB empty file.

**Comment by LeoNatan** [comment]
Hmm not good. I’ll look and fix it.

**Comment by LeoNatan** [comment]
Fixed.
