### ISSUE TITLE
An Error after clicking "Profiler" the decrypted iOS app injected with Profiler Framework

### ISSUE THREAD

**Issue by YY-Wei** [wix/DetoxInstruments#59]
Use [IPAPatch](https://github.com/Naituw/IPAPatch) to inject External Frameworks to decrypted iOS App.
1.When I inject the [LookinServer.framework](https://cdn.lookin.work/download/framework/LookinServer-0-9-4.zip), everything works without any error.

2.When I inject the Profiler Framework, the injected app can launch
![image](https://user-images.githubusercontent.com/54052330/65774126-457e4280-e170-11e9-9ae9-df7175f4c43a.png)

**but when I click the "Profiler" button, it was terminated with the following error:**

2019-09-27 21:33:26.329862+0800 YouTube[2489:164959] [Profiler] Starting profiling
2019-09-27 21:33:26.338382+0800 YouTube[2489:164959] [error] error: No NSEntityDescriptions in any model claim the NSManagedObject subclass 'DTXRecording' so +entity is confused.  Have you loaded your NSManagedObjectModel yet ?
CoreData: error: No NSEntityDescriptions in any model claim the NSManagedObject subclass 'DTXRecording' so +entity is confused.  Have you loaded your NSManagedObjectModel yet ?
2019-09-27 21:33:26.338643+0800 YouTube[2489:164959] [error] error: +[DTXRecording entity] Failed to find a unique match for an NSEntityDescription to a managed object subclass
CoreData: error: +[DTXRecording entity] Failed to find a unique match for an NSEntityDescription to a managed object subclass

**Comment by LeoNatan** [comment]
Hello,

Again, this looks like a bug on your end. IPAPatch is most likely not injecting the framework bundle properly. The Core Data model is included inside the .framework.

**Comment by LeoNatan** [comment]
https://github.com/wix/DetoxInstruments/blob/1c0254920cbb342d1fa35ee9d346e7d509b17a77/Profiler/DTXProfiler/DTXProfiler.m#L87

Put a breakpoint here and verify what is returned. Should not be nil or an empty array.

**Comment by LeoNatan** [comment]
I think I see the problem:

> - Resources/Bundles:
>   - Other resources or bundles can be placed at IPAPatch/Assets/Resources
>   - Resources will be copied directly to the main bundle of original app

I think this is the problem. It puts resources in the incorrect place.

**Comment by LeoNatan** [comment]
The framework expects that its resources are found in the same bundle as the one containing the code.

**Comment by YY-Wei** [comment]
> The framework expects that its resources are found in the same bundle as the one containing the code.

Thanks for your detailed reply. I will figure it out.
