### ISSUE TITLE
brew cask install detox-instruments is failing

### ISSUE THREAD

**Issue by derrh** [wix/DetoxInstruments#60]
**Description**

    brew tap wix/brew
    brew cask install detox-instruments

fails with the following error:

```
➜  life-extend git:(test-memory-leaks) ✗ brew cask install detox-instruments
Updating Homebrew...
Warning: Cask 'detox-instruments' is unreadable: /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/Casks/detox-instruments.rb:5: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/Casks/detox-instruments.rb:11: syntax error, unexpected ===, expecting end-of-input
=======
^~~
Error: Cask 'detox-instruments' is unreadable: /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/Casks/detox-instruments.rb:5: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/Casks/detox-instruments.rb:11: syntax error, unexpected ===, expecting end-of-input
=======
^~~
```

**Steps to Reproduce**

    brew tap wix/brew
    brew cask install detox-instruments

**Expected Behavior**
Detox Instruments successfully installs

**Screenshots**
NA

**Crash Dump**
NA

**Environment**
 - Model: MacBook Pro (15-inch, 2017)
 - OS: macOS 10.14.6 (18G103)
 - Xcode: Xcode 11.2
 - Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Additional Context**
NA

**Comment by LeoNatan** [comment]
Please follow the instructions in the readme: https://github.com/wix/DetoxInstruments#installation-troubleshooting
