### ISSUE TITLE
profile__build_phase.sh fails with '../DetoxSync.framework/DetoxSync: No such file or directory'

### ISSUE THREAD

**Issue by patBurger** [wix/DetoxInstruments#64]
**Description**
I followed your [Framework Integration Guide](https://github.com/wix/DetoxInstruments/blob/master/Documentation/XcodeIntegrationGuide.md) but when I want to compile the app, I get the following error: 

> openssl enc -aes-256-cbc -d -K 0 -iv 0 -nosalt -in '/Applications/Detox Instruments.app/Contents/SharedSupport/Scripts/../ProfilerFramework/DTXProfiler.framework/Frameworks/DetoxSync.framework/DetoxSync' -out /Users/(...)/Library/Developer/Xcode/DerivedData/(...)/Build/Products/Debug-iphonesimulator/(...)/Frameworks/DTXProfiler.framework/Frameworks/DetoxSync.framework/DetoxSync
(...)/Library/Developer/Xcode/DerivedData/(...)/Build/Products/Debug-iphonesimulator/(...)/Frameworks/DTXProfiler.framework/Frameworks/DetoxSync.framework/DetoxSync: No such file or directory
4520914540:error:02FFF002:system library:func(4095):No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/bio/bss_file.c:255:fopen('(...)/Library/Developer/Xcode/DerivedData/(...)/Build/Products/Debug-iphonesimulator/NewsOne.app/Frameworks/DTXProfiler.framework/Frameworks/DetoxSync.framework/DetoxSync', 'w')
4520914540:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/bio/bss_file.c:257:
Command PhaseScriptExecution failed with a nonzero exit code

**Steps to Reproduce**

- Follow the brew instructions
- Follow instructions in XcodeIntegrationGuide
- Compiling the app

**Expected Behavior**

- compiling doesn't fail

**Environment**

Model: MacBook Pro (15-inch, 2017)
OS: macOS 10.15.2
Xcode: Xcode 11.3
Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
Detox Instruments: 11.12 (11639)

**Comment by patBurger** [comment]
**Possible Solution**

I think it's just a spelling mistake in 'profiler_build_phase.sh' in line 27. 
`rm -fr "${CODESIGNING_FOLDER_PATH}"/Frameworks/"${PROFILER_FRAMEWORK_NAME}"/Frameworks/"${PROFILER_SHIM_FRAMEWORK_NAME}"`

The variable `PROFILER_SHIM_FRAMEWORK_NAME` is undefined so the complete `Frameworks` folder is deleted and DetoxSync is not available anymore.

**Comment by LeoNatan** [comment]
Thanks, fixed. Releasing a new version now.
