### ISSUE TITLE
DTXProfiler.framework damaged on MacOS

### ISSUE THREAD

**Issue by sytolk** [wix/DetoxInstruments#66]
**Description**
I have run with Detox
"test:ios-debug": "detox test --configuration ios.sim.debug -l verbose --take-screenshots all --record-videos failing --record-logs failing --record-performance all --cleanup",

**Environment**
 - Model: MacMini
 - OS: MacOS Catalina 10.15.3
 - Xcode: 11.3.1

**Additional Context**
When I run Detox tests with  [--record-performance all](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md)
![image](https://user-images.githubusercontent.com/1415463/76111448-f96dde80-5fe8-11ea-82a8-4938d24a0a14.png)

I have try `brew cask reinstall detox-instruments` but the same results..

**Comment by LeoNatan** [comment]
What version do you have installed?

**Comment by sytolk** [comment]
I have follow the Installation https://github.com/wix/DetoxInstruments#installation and install the last version

**Comment by LeoNatan** [comment]
And what causes this alert to show up? I've never seen it.

What exactly are you doing?

**Comment by LeoNatan** [comment]
Is this on Catalina?

Try perhaps running Detox Instruments once, then trying to run the test.

**Comment by sytolk** [comment]
Yes this is Catalina alert. It appears when I run detox test

**Comment by LeoNatan** [comment]
Try opening Detox Instruments once. I don't know how this can possibly be triggered by Detox.

**Comment by sytolk** [comment]
This appers to be some security alert from catalina.. After open Detox Instrument from App launcher its have different alert with "Open it" button. Next I can running detox tests without "DTXProfiler is Damaged" and "Move to Bin" message.

**Comment by LeoNatan** [comment]
How odd.
