### ISSUE TITLE
Recording not possible with activity options enabled

### ISSUE THREAD

**Issue by birgernass** [wix/DetoxInstruments#68]
**Description**

With either "Record app activity" or "Record internal React Native activity" or both options enabled the recording never starts. As soon as I stop the profiling session the following error pops up:

> The file “_dtx_recording.sqlite” couldn’t be opened because there is no such file.  

**Steps to Reproduce**

Steps to reproduce the behaviour:
1. Enable either Record app activity or Record internal React Native activity
2. Start profiling session
3. Recording never starts
4. Stop profiling session
5. See error

**Environment**
 - Model: MacBook Pro 2018
 - OS: macOS 10.15.3
 - Xcode: Xcode 11.3.1

**Comment by LeoNatan** [comment]
Hello,
Which React Native version are you using? Could be some incompatibility with a recent RN.

**Comment by birgernass** [comment]
Hello, sure.

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 30.37 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

**Comment by LeoNatan** [comment]
Could I please ask you to create a new RN project at the same version using `react-native init` and see if it works for you then? That version of RN has definitely been tested and working. Thanks

**Comment by birgernass** [comment]
Thanks for your help. I tried react-native init with version 0.61.5 and also 0.62.2 and the problem still occurs with both projects. If there is anything else I could try or logs I could send just let me know.

**Comment by LeoNatan** [comment]
I've just released a new version. Can you please test and see if you can still reproduce this issue?
