### ISSUE TITLE
DTXProfiler framework not found

### ISSUE THREAD

**Issue by brian-perlego** [wix/DetoxInstruments#69]
**Description**
After installing everything, when I launch the app it just crash. I have installed Detox Instruments with brew, include the script and add the FLAGS

**Steps to Reproduce**
Follow the README installation steps

**Expected Behavior**
The app to launch

**Crash Dump**
```
dyld: Library not loaded: @rpath/DTXProfiler.framework/DTXProfiler
  Referenced from: /Users/brian/Library/Developer/CoreSimulator/Devices/DF7A7EBE-F0C0-4E65-8128-F24F3F17658C/data/Containers/Bundle/Application/47784207-2F62-4D6C-B2B4-7AA24FB580C7/Perlego.app/Perlego
  Reason: image not found
```

**Environment**
 - Model: MacBook Pro 2018
 - OS: macOS 10.15.4
 - Xcode: 11.4.1

**iOS Device (please complete the following information):**
 - Model: Simulator
 - OS: iOS 13.4.1
 - Xcode: 11.4.1

**Comment by de-blue** [comment]
me too

**Comment by LeoNatan** [comment]
Thanks guys, I’ll look soon

**Comment by LeoNatan** [comment]
Can you post the contents of the resulting .app folder? Specifically, in the Frameworks folder. Thanks

**Comment by LeoNatan** [comment]
I've just released a new version. Please try again. Since you haven't responded to my request, I am closing the issue. If the issue persists, please post the requested information, as well as your build log from Xcode, and I'll reopen. Thanks
