### ISSUE TITLE
Active performance monitoring and alerting

### ISSUE THREAD

**Issue by simistern** [wix/DetoxInstruments#70]
This may be the wrong place to ask about this, but I am curious how to leverage the data for  from detox instruments reporting in CI, as we are saving it as a circleCI artifact. For example, alerting if certain parameters fall out of bounds (activity across the bridge or memory usage) or even comparing that to a baseline or the previous master build. 

To rephrase, How can detox instruments be leveraged for a long-term role in an application undergoing constant refactoring/feature integration?

**Comment by LeoNatan** [comment]
Hello,

Do you mean in the context of Detox tests, or in iOS tests general?
Generally speaking, it shouldn't matter, as what we do in Detox you can achieve directly using the provided Profiler framework API.
In Detox, we have the `--record-performance` flag, which creates a recording for the tests. Each test has its own entry, which, using the CLI tools that come with Detox Instruments, you can use to split the data in the recording for each test.
We don't have yet a publicly available tool that takes the data and analyzes it. This is out of scope for Detox Instruments. But you can implement it on your own. For example, several strategies you can employ is to look at average CPU and memory usage, and alert if certain threshold is passed. More advanced strategies can be implemented to look at performance trends over numerous tests.
