### ISSUE TITLE
Fatal Profiler Scheme Error

### ISSUE THREAD

**Issue by BurakKartal1** [wix/DetoxInstruments#75]
**Description**
I followed the steps to integrate with XCode. I did not change any part of the code that was provided in the page. Debug scheme is working however when i build release i get this error message.

fatal error: lipo: -extract i386 specified but fat file: ******/Build/Products/Release-iphonesimulator/myapp.app/Frameworks/DTXProfiler.framework/DTXProfiler does not contain that architecture.

**Environment**
 - Model: MacBook Pro 2018
 - OS: MacOS 10.15.5
 - Xcode: 11.6

**iOS Device:**
 - Model: iPhone 11
 - OS: 11.6
 - Xcode: 11.6

**Comment by LeoNatan** [comment]
Hello,
What is your minimum deployment target?

**Comment by LeoNatan** [comment]
The minimum deployment target of the Profiler framework is 12.0 (but should work with any version in release). Starting with iOS 11, Apple only ships iOS in 64-bit, and thus targets with minimum deployment target of iOS 11 and above build for 64-bit only. That translates to x86-64 for simulators. You need to raise the minimum deployment target if your app to 11.0 and only build for 64-bit.
