### ISSUE TITLE
Xcode project becomes entirely dependent on Detox Instruments desktop application being installed.

### ISSUE THREAD

**Issue by FilipMaslovaric** [wix/DetoxInstruments#79]
**Description**
Detox Instruments (application) must be installed in order to build and run the iOS application one is developing, once the Xcode integration steps are completed (adding Other Linker flags, build phase scripts)

**Steps to Reproduce**
1. Try to build your iOS application without having first installed Detox Instruments, but all other integration steps have been completed (e.g. someone other than yourself, who isn't looking to performance profile, building and running the app)
2. Get error.

**Expected Behavior**
The iOS app should be able to be built and run without the need to have Detox Instruments (application) installed on the machine, e.g. someone other than yourself needing to run the iOS app on their machine, but not looking to do performance profiling.

**Crash Dump**
```
ld: warning: directory not found for option '-F/Users/filip.maslovaric/Library/Developer/Xcode/DerivedData/ReactNative-xxxxxxxxx/Build/Products/Debug-iphonesimulator/xxxxx.app/Frameworks'
ld: framework not found DTXProfiler
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**Environment**
 - Model: Irrelevant
 - OS: Irrelevant
 - Xcode: Xcode 12

**iOS Device (please complete the following information):**
 - Model: Irrelevant
 - OS: Irrelevant
 - Xcode: Xcode 12

**Comment by LeoNatan** [comment]
Unfortunately, I haven’t found a way to achieve that. Once you add the linker flag in project settings, it looks for the framework you specified. There is no way to specify a a linked product from inside the script. If you have ideas, I’d like to hear. One option is to duplicate the target, and have one target with the link, while another remains clean. But that, too, has limitations; if you import and use the Profiler APIs, it will not compile.

**Comment by LeoNatan** [comment]
Also, what is the difference between something like CocoaPods and this? If a project is made to use CocoaPods, all developers would need to have it on their machines. Likewise with this tool.

**Comment by FilipMaslovaric** [comment]
Ok then.

![image](https://user-images.githubusercontent.com/29298651/99141307-df1af300-2695-11eb-8ced-428ce50f766b.jpeg)

This profiling tool is not the same as a package manager in terms of necessity to being able to run a bundle of code. That dependency and necessity is forced artificially by way of how you've integrate the profiler with the rest of the code, not by virtue of what it does to enable the rest of the code to run.

That is how it is different to CocoaPods.

My team and I had already considered utilising a separate "Profiling" target in Xcode, but that then does present other limitations as you've mentioned. One potential solution is to utilise the React Native Scheme Manager library, as you have to also circumvent the hard coded config that react native has that ties it to just Debug and Release schemes. In other words, you'd need a further dependency to deal with this unexpected and undocumented dependency. Sure if I had been more knowledgeable about Xcode and pure native iOS development I might have spotted that the linker flag would present this problem, but to most React Native devs, this will come as a surprise if they have more than just themselves wanting to check out and run the project in Xcode locally.

The very least that should be done here is to state clearly in the documentation that the Detox Instruments desktop application will be required to be installed once the integration steps are carried out, in order for the code to be build and to run the app (even if not profiling). A better thing to do would be to also include this in the Troubleshooting guide (referencing the above errors).

Not waiting even 12 hours for a reply, closing the issue, and then marking is as **invalid** is quite rude.

**Comment by LeoNatan** [comment]
No rudeness was intended, please don’t get insulted by our issue labels. To prevent a further “insult”, I’ve created a new label.

I closed the issue because I didn’t find anything that I can do from a technical standpoint. The framework needs to be linked with the binary, and the only way to do that is either adding it in Xcode or specifying the linker flag. We’ve already gone the more convenient way and not require people to touch their Xcode projects too much, for exactly the reason you mention; not everyone is familiar with it. I agree with you that this should be stated in the documentation, and will update it soon accordingly. 

Also, posting image macros and being flippant on GitHub issues isn’t very professional or courteous.

**Comment by LeoNatan** [comment]
> This profiling tool is not the same as a package manager in terms of necessity to being able to run a bundle of code. That dependency and necessity is forced artificially by way of how you've integrate the profiler with the rest of the code, not by virtue of what it does to enable the rest of the code to run.

Given all the constraints, we believe this is the most effective way to integrate the project. We have a large experience with RN developers who are afraid to even touch Xcode, let alone have to manage manual linking of the framework. But even if they did manually link it, it would still not fix your issue. You are linking a framework into the project. This is not JS.

**Comment by FilipMaslovaric** [comment]
> No rudeness was intended, please don’t get insulted by our issue labels. To prevent a further “insult”, I’ve created a new label.

That is a much better label for what is intended, agreed.

> I closed the issue because I didn’t find anything that I can do from a technical standpoint. The framework needs to be linked with the binary, and the only way to do that is either adding it in Xcode or specifying the linker flag. We’ve already gone the more convenient way and not require people to touch their Xcode projects too much, for exactly the reason you mention; not everyone is familiar with it. I agree with you that this should be stated in the documentation, and will update it soon accordingly.

Thank you for expanding on the limitations behind the inability to address the issue. Thank you also for undertaking to update the documentation to cover this issue. I wouldn't have raised it had it not been experienced by several of my team members and other stakeholders (who needed to run the project but had no need to performance profile). Had I known that the desktop app would need to be installed to run the project at all, from then on, I would have included it as a pre-requisite in our project (like CocoaPods).

> Also, posting image macros and being flippant on GitHub issues isn’t very professional or courteous.

Touche. My point about drawing a false equivalence between the two pieces of technology stands.
